# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Testing

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    changedfiles:
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
            common: ${{ steps.changes.outputs.common}}
            year2020: ${{ steps.changes.outputs.year2020 }}
            year2021: ${{ steps.changes.outputs.year2021 }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Determine tests to run
                id: changes
                run: |
                    echo "::set-output name=common::$([ "$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep *common*)" ] &&  echo :adventofcode.common:test)"
                    echo "::set-output name=year2020::$([ "$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep *2020*)" ] &&  echo :adventofcode.year2020:test)"
                    echo "::set-output name=year2021::$([ "$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep *2021*)" ] &&  echo :adventofcode.year2021:test)"

    build:
        if: ${{ needs.changedfiles.outputs.common || needs.changedfiles.outputs.year2020 || needs.changedfiles.outputs.year2021 }}
        needs: changedfiles
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   name: Test with Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: |
                        clean
                        ${{ needs.changedfiles.outputs.common }}
                        ${{ needs.changedfiles.outputs.year2020 }}
                        ${{ needs.changedfiles.outputs.year2021 }}
