# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Checks

on:
    pull_request:
        branches: [ master ]

jobs:
    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - name: Lint
              run: mvn -ntp -U spotless:check
    test:
        name: Testing
        strategy:
            matrix:
                version: [ '17', '21', '22' ] 
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5
            -   name: 'Set up JDK ${{ matrix.version }}'
                uses: actions/setup-java@v4
                with:
                    java-version: '${{ matrix.version }}'
                    distribution: 'temurin'
            -   name: Test
                run: mvn -ntp -U -Dspotless.check.skip=true test
